language: node_js

sudo: false

os:
  - osx
  - linux

node_js: 10

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      sleep 3;
    fi
install: 
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent

cache: node_modules