// Generated from syntaxes/intouch.tmLanguage.json by scripts/generate-language-data.js.
// Do not edit this file manually.

export interface KnownFunction {
	name: string;
	category: string;
	sourceComment: string;
}

export const KNOWN_FUNCTIONS: readonly KnownFunction[] = [
	{
		"name": "Abs",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "Ack",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "ActivateApp",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "AddPermission",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "Alarmkommentare",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "almAckAll",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almAckDisplay",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almAckGroup",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almAckPriority",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almAckRecent",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almAckSelect",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almAckSelectedGroup",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almAckSelectedPriority",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almAckSelectedTag",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almAckTag",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almDefQuery",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almMoveWindow",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almQuery",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSelectAll",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSelectGroup",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSelectionCount",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSelectItem",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSelectPriority",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSelectTag",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSetQueryByName",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almShowStats",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSuppressAll",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSuppressDisplay",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSuppressGroup",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSuppressPriority",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSuppressRetain",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSuppressSelected",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSuppressSelectedGroup",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSuppressSelectedPriority",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSuppressSelectedTag",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almSuppressTag",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almUnselectAll",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "almUnsuppressAll",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "AnnotateLayout",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APAntriebStatistik",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "APMonatAktualisierenZaehler1",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "APMonatAktualisierenZaehler2",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "APMonatAktualisierenZaehler3",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "AppButonsConfig",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "ApplicomToUAReference",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "APTagAktualisierenZaehler1",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "APTagAktualisierenZaehler2",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "APTagAktualisierenZaehler3",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "APUFindAlarmGroupInstance",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUFindFileInstance",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUFindPrinterInstance",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUGetAlarmGroupText",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUGetConfigurationFilePath",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUGetInstanceCount",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUGetPrinterJobCount",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUGetPrinterName",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUGetPrinterStatus",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUGetQueryAlarmState",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUGetQueryFromPriority",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUGetQueryProcessingState",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUGetQueryToPriority",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUIsInstanceUsed",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUSetAlarmGroupText",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUSetQueryAlarmState",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUSetQueryFromPriority",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUSetQueryToPriority",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUSetTimeoutValues",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUStartInstance",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUStartQuery",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUStopInstance",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUStopQuery",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APUTranslateErrorCode",
		"category": "IT-functions Ground Teil 1",
		"sourceComment": "IT-functions Ground Teil 1"
	},
	{
		"name": "APZaehlerAbfragen",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "ArcCos",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "ArcSin",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "ArcTan",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "AttemptInvisibleLogon",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "BDEDatenLesen",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "BDEDatenSpeichern",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "BDEDatenSuchen",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "BDESchichtSchreiben",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "BDESchichtwerteDatenOK",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "BDESchichtwerteZuweisen",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "BDETageswerteDatenOK",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "BDETageswerteSchreiben",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "BDETageswerteZuweisen",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "BZBetriebsstunden",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "BZMonatAktualisierenZaehler1",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "BZMonatAktualisierenZaehler2",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "BZMonatAktualisierenZaehler3",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "BZTagAktualisierenZaehler1",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "BZTagAktualisierenZaehler2",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "BZTagAktualisierenZaehler3",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "BZZaehlerAbfragen",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "ChangePassword",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "ChangeWindowColor",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "Clip_cursor",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "ConvertTemp",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "Cos",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "CreateFilenameFromDate",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "DateTimeGMT",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "DialogStringEntry",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "DialogValueEntry",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "DText",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "EnableDisableKeys",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "Exp",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "ExterneModuleUeberwachen",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "FileCopy",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "FileDelete",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "FileMove",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "FilePrint",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "FileReadFields",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "FileReadMessage",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "FileSelect",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "FileWriteFields",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "FileWriteMessage",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "FUWerte",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "GeoArea",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "GeoEqualSideArea",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "GeoVolume",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "GetAccountStatus",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "GetCursorPosition",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "GetDiscOffMsg",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "GetDiscOnMsg",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "GetFullTopic",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "GetNodeName",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "GetPropertyD",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "GetPropertyI",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "GetPropertyM",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "GetSplittByIndex",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "GetWindowName",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HDWExport",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "HerBACKUP",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "HerGATEWAYanzeigeAktualisieren",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "HerGATEWAYStatusLesen",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "HerGATEWAYtriggerFreigabe",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "HerGATEWAYueberwachen",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "HerProViewStart",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "HerProViewStartV",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "Hide",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "Hide_cursor",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "HideAllPLS",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "HideSelf",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTGetLastError",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTGetPenName",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTGetTimeAtScooter",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTGetTimeStringAtScooter",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTGetValue",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTGetValueAtScooter",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTGetValueAtZone",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTScrollLeft",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTScrollRight",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTSelectTag",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTSetPenName",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTUpdateToCurrentTime",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTZoomIn",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "HTZoomOut",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "Hubbodensteuerung",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "InfoAppActive",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "InfoAppStatus",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "InfoAppTitle",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "InfoAppTitleExpand",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "InfoDisk",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "InfoDosEnv",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "InfoFile",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "InfoInTouchAppDir",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "InfoResources",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "InfoWinEnv",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "INIReadInteger",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "INIReadString",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "INIWriteInteger",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "INIWriteString",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "Int",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "InTouchVersion",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "InvisibleVerifyCredentials",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IODisableFailover",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IOForceFailover",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IOGetAccessNameStatus",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IOGetActiveSourceName",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IOGetApplication",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IOGetNode",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IOGetTopic",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IOReinitAccessName",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IOReinitialize",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IORRGetItemActiveState",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "IORRGetSystemInfo",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "IORRWriteState",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "IOSetAccessName",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IOSetItem",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IOSetRemoteReferences",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IOStartUninitConversations",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IsAnyAsyncFunctionBusy",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IsAssignedRole",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "IsNodeAppRunning",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXAppActivate",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "ITXCheckDate",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "ITXConvertDate",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "ITXConvertDateString",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "ITXConvertDateTime",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "ITXConvertDateTimeString",
		"category": "IT-functions Ground Teil 2",
		"sourceComment": "IT-functions Ground Teil 2"
	},
	{
		"name": "ITXCreateDate",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ITXCreateDateTime",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ITXCreateDateTimeUTC",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ITXCreateDirectory",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXCreateSubDirectory",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXGetProfileInt",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXGetProfileString",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXPutProfileInt",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXPutProfileString",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXRemoveDirectory",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXRemoveSubDirectory",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXResizeApplication",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXSetLocalTime",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXSetSystemDate",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXSetSystemTime",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXShowHelpByNumber",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ITXShowHelpByString",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ITXStartAppInDirectory",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "ITXWindowCtrl",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "KonfigLesen",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "KonfigSpeichern",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "LaunchTagViewer",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "loadVarFromDB",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "Log",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "LogMessage",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "LogN",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "Logoff",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "LogonCurrentUser",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "MADatum",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "MAKurvenAbfragen",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "MAKurvenProfileAbfragen",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "MessageBox",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "MetFromStdFluid",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "MetFromStdLinear",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "MetFromStdWeight",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "Mouse",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "MoveWindow",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "NumberRecipes",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "OnlineHilfeAufrufen",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "OpenWindowsList",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "Pi",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "PlaySound",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "PostLogonDialog",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "PrintHT",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "PrintScreen",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "PrintWindow",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptGetTrendType",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptLoadTrendCfg",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptPanCurrentPen",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptPanTime",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptPauseTrend",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptRefreshTrend",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptSaveTrendCfg",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptSetCurrentPen",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptSetPen",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptSetPenEx",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptSetTimeAxis",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptSetTimeAxisToCurrent",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptSetTrend",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptSetTrendType",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptZoomCurrentPen",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ptZoomTime",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "PwdUserAdd",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "PwdUserDelete",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "PwdUserEdit",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "PwdUserGetIndex",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "PwdUserRead",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "QFFilter",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "QFFilterRegler15Schritt",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "QFLuftwerte",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "QFRinne",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "QueryGroupMembership",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "RecipeDelete",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "RecipeGetMessage",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "RecipeLoad",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "RecipeSave",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "RecipeSelectNextRecipe",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "RecipeSelectPreviousRecipe",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "RecipeSelectRecipe",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "RecipeSelectUnit",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "ReloadWindowViewer",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "RestartWindowViewer",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "Restore_clip",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "Round",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "Scripsnippets_Intouch",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SendKeys",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "SendMail",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "SendSMTPMail",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "SendSMTPMailwAttachment",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "SessionUserInfoAkt",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "SetCursorPosition",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "SetPropertyD",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "SetPropertyI",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "SetPropertyM",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "SetReferenceBool",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "SetReferenceByte",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "SetReferenceDINT",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "SetReferenceDINTs",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "SetReferenceINT",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SetReferenceMerkerByte",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "SetReferenceReal",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "SetReferenceString",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "SetReferenceWord",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "SetSMELAccessname",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SetTagEU",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "SetTopicTest",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SetVarInputBoolsch",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "SetVarToggleBoolsch",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "SetWindowPrinter",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "Sgn",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "Show",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "Show_cursor",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "ShowAt",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ShowHome",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "ShowTopLeftAt",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "Sin",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "SMELCPUPopup",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SMELEditorAufrufen",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SMELInfo",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SMELInfoView",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SMELSQL",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SmelUpdateDB",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SMELUpdateDBWTaV",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SMELUpdateDBWTnV",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "Sollwertaenderung",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "SPCEXSetDataset",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SPCEXSetEndDate",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SPCEXSetEndTime",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SPCEXSetOutputFile",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SPCEXSetProduct",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SPCEXSetStartDate",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SPCEXSetStartTime",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SpecialAccessChangeGUI",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SpecialAccessChangePw",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SpecialAccessCheckGUI",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SpeciallAccessCheckPw",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "SQLAppendStatement",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLClearParam",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLClearStatement",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLClearTable",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLCommit",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLConnect",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLCreateTable",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLDelete",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLDisconnect",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLDropTable",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLEnd",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLErrorMsg",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLExecute",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLFirst",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLGetRecord",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLInsert",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLInsertEnd",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLInsertExecute",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLInsertPrepare",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLLast",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLLoadStatement",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLManageDSN",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLNext",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLNumRows",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLPrepareStatement",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLPrev",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLRollback",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLSelect",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLSetParamChar",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLSetParamDate",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLSetParamDateTime",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLSetParamDecimal",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLSetParamFloat",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLSetParamInt",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLSetParamLong",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLSetParamNull",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLSetParamTime",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLSetStatement",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLTransact",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLUpdate",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "SQLUpdateCurrent",
		"category": "Intouch AddOns functions",
		"sourceComment": "Intouch AddOns functions"
	},
	{
		"name": "Sqrt",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "StartApp",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "StartEP2",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "StartEP3",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "StatusExtApp",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "StatusleistenInfofelder",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "StdFromMetFluid",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "StdFromMetLinear",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "StdFromMetWeight",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "StringASCII",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringChar",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringCompare",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringCompareEncrypted",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "StringCompareNoCase",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringFromGMTTimeToLocal",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringFromIntg",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringFromReal",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringFromTime",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringFromTimeLocal",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringInString",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringLeft",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringLen",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringLower",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringMid",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringReplace",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringRight",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringSpace",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringTest",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringToIntg",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringToReal",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringTrim",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "StringUpper",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "SwitchDisplayLanguage",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "SWReal",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "SysBeep",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "SystemIsNT",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "sysuhrzeitsynchron",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "TABAntrieb",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "TABCommentTo2z",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "TABHER012AZ",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "TABHER012AZS",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "TABHER012EA",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "TABHER012EAF",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "TABHER012EAFB",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "TABHER012EAS",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "TABHER062",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "TABResetPLSReferences",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "TABWILO",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "TagExists",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "Tan",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "Text",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "Trunc",
		"category": "IT-functions-Math",
		"sourceComment": "IT-functions-Math"
	},
	{
		"name": "TseGetClientId",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "TseGetClientNodeName",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "TseQueryRunningOnClient",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "TseQueryRunningOnConsole",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "UTCDateTime",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "VZMonatAktualisierenZaehler1",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "VZMonatAktualisierenZaehler2",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "VZMonatAktualisierenZaehler3",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "VZTagAktualisierenZaehler1",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "VZTagAktualisierenZaehler2",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "VZTagAktualisierenZaehler3",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "VZVerbrauchsdaten",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "VZZaehlerAbfragen",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "WBBetriebsstunden",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "wcAddItem",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wcClear",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wcDeleteItem",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wcDeleteSelection",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wcErrorMessage",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wcFindItem",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wcGetItem",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wcGetItemData",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wcInsertItem",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wcLoadList",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wcLoadText",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wcSaveList",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wcSaveText",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wcSetItemData",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WebCPUaufrufen",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "WindowState",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WVVerbrauchsdaten",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "wwalmdbtrigger",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "WWAlwaysOnTop",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWBeep32",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWCntx32",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWContext",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWControl",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWControlPanel",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWDosCommand",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWExecute",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWGetServiceExeName",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "WWGetServiceName",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "WWGetServiceStatus",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "WWIsDayLightSaving",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWMoveWindow",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWMultiMonitorNode",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWPoke",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWPrimaryMonitorHeight",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWPrimaryMonitorWidth",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWRequest",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWServiceControl",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "WWServiceControlError",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "WWShutDownWin95",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "WWShutDownWinNT40",
		"category": "IT-functions-System",
		"sourceComment": "IT-functions-System"
	},
	{
		"name": "WWStartApp",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "wwStringFromTime",
		"category": "Intouch String functions",
		"sourceComment": "Intouch String functions"
	},
	{
		"name": "WWVirtualMonitorHeight",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "WWVirtualMonitorWidth",
		"category": "IT-functions Ground Teil 3",
		"sourceComment": "IT-functions Ground Teil 3"
	},
	{
		"name": "xAnlagenConfig",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "xAT01Config",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xAT02Config",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xAT03Config",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xAT04Config",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xAT05Config",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xAT06Config",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xAT07Config",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xAT08Config",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xAT09Config",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xAT10Config",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xBZVZSettings",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "xGatawaySettings",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "xHerDebug",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "xHerDebugL",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "xHerGATEWAYSettings",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "xHerGatewayStart",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xKonfigSpeichern",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xLoggingConfig",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "xLogoffOnTSMaster",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xLogoutFromStationTS",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xSetDateiPfade",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "xSetDeverloper",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xSetSQLConfig",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "xSetTSStation",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "xSetUhrzeitserver",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 1"
	},
	{
		"name": "xSetupDeploymentMode",
		"category": "Hermes helper",
		"sourceComment": "Hermes ground-program QuickFunctions"
	},
	{
		"name": "xSTATION1BiosName",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 2"
	},
	{
		"name": "xSTATION2BiosName",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 2"
	},
	{
		"name": "xSTATION3BiosName",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 2"
	},
	{
		"name": "xSTATION4BiosName",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 2"
	},
	{
		"name": "xSTATION5BiosName",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 2"
	},
	{
		"name": "xSTATION6BiosName",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 2"
	},
	{
		"name": "xSTATION7BiosName",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 2"
	},
	{
		"name": "xSTATION8BiosName",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 2"
	},
	{
		"name": "xSTATION9BiosName",
		"category": "Hermes helper",
		"sourceComment": "Hermes Own functions 2"
	}
] as const;
